### ISSUE TITLE
Set MaxBuffer as argument in the command line

### ISSUE THREAD

**Issue by paolocarrasco** [SoCreate/angular-playground#155]
### Versions

```
angular-playground version 5.1.5
```

```
Angular CLI: 6.1.2
Node: 10.9.0
OS: darwin x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.2
@angular/cdk                      6.3.0
@angular/cli                      6.1.2
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.3.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* There is a large application where we want to use Playground (we have plans to use split it up, but we want this working first).
* Followed the instructions in the `playground.it` page to deploy the Angular Playground output. 
* It was configured a build step in the `package.json` file:
```
"playground-build": "angular-playground --build"
```
* Run `npm run playground-build`.

### Observed Behavior
```
└─▪ npm run playground-build

> the-client@0.0.0 playground-build /Users/paolocarrasco/Documents/repos/the-client
> angular-playground --build

Successfully compiled sandbox files.
Building for production with sandboxes...
/Users/paolocarrasco/Documents/repos/the-client/node_modules/angular-playground/dist/bin/src/build-angular-cli.js:26
                throw err;
                ^

RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:360:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:639:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! the-client@0.0.0 playground-build: `angular-playground --build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-client@0.0.0 playground-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paolocarrasco/.npm/_logs/2018-11-06T20_52_43_176Z-debug.log

```

### Desired Behavior
The playground build outcome should be generated.

### Any other details that may be useful
This is fixed by manually adding the `maxBuffer` to the execution of the `ng build` in the `buildAngularCli` function inside the `build-angular-cli.js` file, as it can be seen in the following chunk:
```javascript
function buildAngularCli(appName, baseHref) {
    return __awaiter(this, void 0, void 0, function* () {
        let isInstalled = yield serviceWorkerIsInstalled();
        if (!isInstalled) {
            throw new Error('\n\nError: --build requires @angular/service-worker to be installed locally: \n' +
                'try running "npm install @angular/service-worker" then run "angular-playground --build" \n' +
                'see docs: https://github.com/angular/angular-cli/wiki/build#service-worker\n\n');
        }
        console.log('Building for production with sandboxes...');
        // Cannot build w/ AOT due to runtime compiler dependency
        child_process_1.exec(`ng build ${appName} --prod --aot=false --base-href=${baseHref}`,
            {maxBuffer: 10240 * 1024},
            (err, stdout, stderr) => {
            if (err)
                throw err;
            console.log(stdout);
        });
    });
}
```

I think I can create a PR with the changes that add this as argument in the command line but I didn't find a test for the `build-angular-cli.ts` file, unless this feature or something similar is in your plans.

**Comment by paolocarrasco** [comment]
Any news about this? We need this change to deploy it.

**Comment by paolocarrasco** [comment]
Thank you guys! You rock! 🎊 🎉 🎈 

![legendary](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)
