### ISSUE TITLE
Cannot install Angular-Playground

### ISSUE THREAD

**Issue by suryasarafe** [SoCreate/angular-playground#230]
### Versions
```
latest
```

```
Angular CLI: 8.3.20
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
```

### Repro steps
* Step 1
`ng new myproject`
* Step 2
`ng add angular-playground` (not working)
and
`npm i angular-playground` (not working)
* Step 3
`npm install --save core-js@^3`
then repeat step 2

### Observed Behavior
```
An unhandled exception occurred: npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Ujang - HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ujang - HP\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\project\other\angular\angular-try-routing\node_modules\weak-napi
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN axobject-query@2.1.1 requires a peer of eslint@^5 || ^6 but none is installed. You must install
peer dependencies yourself.
npm WARN jest-image-snapshot@2.11.1 requires a peer of jest@>=20 <=24 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ujang - HP\AppData\Roaming\npm-cache\_logs\2019-12-13T06_47_37_267Z-debug.log
Package install failed, see above.
See "C:\Users\Ujang~1\AppData\Local\Temp\ng-vdi6wp\angular-errors.log" for further details.

```

### Desired Behavior
```
I already try with another system (windows, mac, other windows) still no luck,
How to solve this issue ? or any online playground.?
```

### Any other details that may be useful (optional)
thank you

**Comment by timstoddard** [comment]
Hi @suryasarafe, it looks like node-gyp is causing issues. See [this comment](https://github.com/SoCreate/angular-playground/issues/228#issuecomment-561777886) for how to fix it. Let us know if that does not work for you.

**Comment by suryasarafe** [comment]
Hi @timstoddard, thanks for your answer, now it working. (but so many app installed that i don't know what and why it's there)

But Thank you.
