### ISSUE TITLE
Error when running add angular-playground

### ISSUE THREAD

**Issue by andreaslarssen** [SoCreate/angular-playground#233]
### Versions
```
None
```

```
Angular CLI: 8.3.22
Node: 12.14.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router


Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.22
@angular-devkit/build-angular      0.803.22
@angular-devkit/build-ng-packagr   0.803.22
@angular-devkit/build-optimizer    0.803.22
@angular-devkit/build-webpack      0.803.22
@angular-devkit/core               8.3.22
@angular-devkit/schematics         8.3.22
@angular/cli                       8.3.22
@ngtools/webpack                   8.3.22
@schematics/angular                8.3.22
@schematics/update                 0.803.22
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2

```

### Repro steps

* Step 1
```
ng new my-workspace --create-application=false
```
* Step 2
```
ng add angular-playground
```

### Observed Behavior
```
Installing packages for tooling via npm.
An unhandled exception occurred: Package install failed.
See "/tmp/ng-8ll8s6/angular-errors.log" for further details.
```

### Desired Behavior
```
Great success! Can you not add angular-playground to a workspace? Do you need an app?
```

**Comment by andreaslarssen** [comment]
EDIT: This also happen when I create a workspace w/ an app. 

The "/tmp/ng-8ll8s6/angular-errors.log" log:
```
[error] Error: Package install failed.
    at Object.installPackage (/home/name/web/ff-ngx-components/node_modules/@angular/cli/tasks/install-package.js:37:15)
    at AddCommand.run (/home/name/web/ff-ngx-components/node_modules/@angular/cli/commands/add-impl.js:113:27)
    at async AddCommand.validateAndRun (/home/name/web/ff-ngx-components/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/home/name/web/ff-ngx-components/node_modules/@angular/cli/models/command-runner.js:186:24)
    at async default_1 (/home/name/web/ff-ngx-components/node_modules/@angular/cli/lib/cli/index.js:54:31)
```

**Comment by lurock** [comment]
You must have an app to install Angular Playground into your workspace.  If you do not when installing it returns a message saying "Your app must have at least 1 project to use Playground."

I have tested the following installations and here was my results:

```
Angular CLI: 8.3.22
Node: 12.14.1
OS: win32 x64
Angular:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.22
@angular-devkit/core         8.3.22
@angular-devkit/schematics   8.3.22
@schematics/angular          8.3.22
@schematics/update           0.803.22
rxjs                         6.4.0

```
### Test create workspace without app

Commands Run:
```
ng new my-workspace-without-app --create-application=false

cd my-workspace-without-app

ng add angular-playground
```

Results:

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Your app must have at least 1 project to use Playground.
```

### Test create workspace with app

Commands Run:
```
ng new my-workspace-with-app

cd my-workspace-with-app

ng add angular-playground
```

Results:

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
CREATE angular-playground.json (82 bytes)
CREATE src/main.playground.ts (294 bytes)
UPDATE package.json (1382 bytes)
UPDATE angular.json (5309 bytes)
```

**Comment by andreaslarssen** [comment]
Yeah, when I run add angular-playground, I get the first line, but then the error listed above. If I run it again, it installs, but has not finished the firste step.

Anyways, I've moved on to Storybook.
